# Generated by Django 2.1.1 on 2018-11-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox', '0002_auto_20181120_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excel',
            old_name='old_FileDf',
            new_name='old_FileStr',
        ),
    ]
