# Generated by Django 2.1.1 on 2018-11-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox', '0004_auto_20181120_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excel',
            old_name='old_FileStr',
            new_name='old_fileStr',
        ),
    ]
