# Generated by Django 2.1.1 on 2018-11-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox', '0005_auto_20181120_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='date_modified_past',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excel',
            name='old_fileStr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
