# Generated by Django 2.1.1 on 2018-10-17 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Book',
        ),
    ]
