# Generated by Django 2.1.1 on 2018-11-16 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20181116_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='realtor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor'),
        ),
    ]
